version: '3'

services:
  nats:
    image: nats:2.2.0-scratch
    command: -p 4444
    ports:
      - 4444:4444

  # jaeger:
  #   image: jaegertracing/all-in-one:1.7
  #   ports:
  #     - 6831:6831/udp
  #     - 6832:6832/udp
  #     - 16686:16686
  # command: --log-level=debug
